### ISSUE TITLE
MilightWWCWZone should extend from env.devices.DimmerActuator?

### ISSUE THREAD

**Issue by michbeck100** [mwittig/pimatic-milight-reloaded#6]
I've seen that MilightWWCWZone has methods to dim the light. Why does this class extend from env.devices.SwitchActuator instead of env.devices.DimmerActuator?

**Comment by mwittig** [comment]
Because env.devices.DimmerActuator only provides support for setting absolute dimming values. However, the MilightWWCWZone control layer only supports relative changes, ie. dim up/down. 

I thought about emulating absolute dimming, but this would result in sending 38 commands in the worst case for a single dim value.
